application: hbuhsd-help-desk
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /static
  static_dir: static
  expiration: "30d"

- url: /.*
  script: app.py
  login: required
